//name : main
//source_file : <closed file 'main.c', mode 'w' at 0x7fd408852150>

///+============================================================================+
///|                                                                            |
///|                     This file was generated by Chips                       |
///|                                                                            |
///|                                  Chips                                     |
///|                                                                            |
///|                      http://github.com/dawsonjon/Chips-2.0                 |
///|                                                                            |
///|                                                             Python powered |
///+============================================================================+
module main(exception);
  integer file_count;
  parameter  stop = 3'd0,
  instruction_fetch = 3'd1,
  operand_fetch = 3'd2,
  execute = 3'd3,
  load = 3'd4,
  wait_state = 3'd5,
  divide = 3'd6,
  multiply = 3'd7;
  reg [31:0] timer;
  reg [63:0] timer_clock;
  reg [15:0] program_counter;
  reg [15:0] program_counter_1;
  reg [15:0] program_counter_2;
  reg [44:0] instruction;
  reg [4:0] opcode_2;
  reg [3:0] a;
  reg [3:0] b;
  reg [3:0] z;
  reg write_enable;
  reg [3:0] address_a_2;
  reg [3:0] address_b_2;
  reg [3:0] address_z_2;
  reg [3:0] address_z_3;
  reg [31:0] load_data;
  reg [31:0] write_output;
  reg [31:0] write_value;
  reg [31:0] read_input;
  reg [15:0] literal_2;
  reg [31:0] a_hi;
  reg [31:0] b_hi;
  reg [31:0] a_lo;
  reg [31:0] b_lo;
  reg [63:0] long_result;
  reg [31:0] result;
  reg [15:0] address;
  reg [31:0] data_out;
  reg [31:0] data_in;
  reg [31:0] carry;
  reg clk;
  reg rst;
  reg [7:0] state;
  output reg exception;
  reg [28:0] instructions [224:0];
  reg [31:0] memory [1023:0];
  reg [31:0] registers [15:0];
  wire [31:0] operand_a;
  wire [31:0] operand_b;
  wire [31:0] register_a;
  wire [31:0] register_b;
  wire [15:0] literal;
  wire [4:0] opcode;
  wire [3:0] address_a;
  wire [3:0] address_b;
  wire [3:0] address_z;
  wire [15:0] load_address;
  wire [15:0] store_address;
  wire [31:0] store_data;
  wire  store_enable;
  wire  forward_a;
  wire  forward_b;
  reg [31:0] shifter;
  reg [32:0] difference;
  reg [31:0] divisor;
  reg [31:0] dividend;
  reg [31:0] quotient;
  reg [31:0] remainder;
  reg quotient_sign;
  reg dividend_sign;
  reg [31:0] product_a;
  reg [31:0] product_b;
  reg [31:0] product_c;
  reg [31:0] product_d;

  //////////////////////////////////////////////////////////////////////////////
  // CLOCK AND RESET GENERATION                                                 
  //                                                                            
  // This file was generated in test bench mode. In this mode, the verilog      
  // output file can be executed directly within a verilog simulator.           
  // In test bench mode, a simulated clock and reset signal are generated within
  // the output file.                                                           
  // Verilog files generated in testbecnch mode are not suitable for synthesis, 
  // or for instantiation within a larger design.
  
  initial
  begin
    rst <= 1'b1;
    #50 rst <= 1'b0;
  end

  

  //////////////////////////////////////////////////////////////////////////////
  // MEMORY INITIALIZATION                                                      
  //                                                                            
  // In order to reduce program size, array contents have been stored into      
  // memory at initialization. In an FPGA, this will result in the memory being 
  // initialized when the FPGA configures.                                      
  // Memory will not be re-initialized at reset.                                
  // Dissable this behaviour using the no_initialize_memory switch              
  
  initial
  begin
  end


  //////////////////////////////////////////////////////////////////////////////
  // INSTRUCTION INITIALIZATION                                                 
  //                                                                            
  // Initialise the contents of the instruction memory                          
  //
  // Intruction Set
  // ==============
  // 0 {'literal': True, 'op': 'literal'}
  // 1 {'literal': True, 'op': 'addl'}
  // 2 {'literal': True, 'op': 'call'}
  // 3 {'literal': False, 'op': 'stop'}
  // 4 {'literal': False, 'op': 'load'}
  // 5 {'literal': False, 'op': 'equal'}
  // 6 {'literal': True, 'op': 'jmp_if_true'}
  // 7 {'literal': True, 'op': 'goto'}
  // 8 {'literal': False, 'op': 'store'}
  // 9 {'literal': False, 'op': 'add'}
  // 10 {'literal': False, 'op': 'subtract'}
  // 11 {'literal': False, 'op': 'multiply'}
  // 12 {'literal': False, 'op': 'divide'}
  // 13 {'literal': False, 'op': 'shift_left'}
  // 14 {'literal': False, 'op': 'shift_right'}
  // 15 {'literal': False, 'op': 'and'}
  // 16 {'literal': False, 'op': 'or'}
  // 17 {'literal': False, 'op': 'xor'}
  // 18 {'literal': False, 'op': 'return'}
  // Intructions
  // ===========
  
  initial
  begin
    instructions[0] = {5'd0, 4'd3, 4'd0, 16'd0};///home/dawsonjon/main.c : 49 {'literal': 0, 'z': 3, 'trace': /home/dawsonjon/main.c : 49, 'op': 'literal'}
    instructions[1] = {5'd0, 4'd4, 4'd0, 16'd0};///home/dawsonjon/main.c : 49 {'literal': 0, 'z': 4, 'trace': /home/dawsonjon/main.c : 49, 'op': 'literal'}
    instructions[2] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 49 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 49, 'op': 'addl'}
    instructions[3] = {5'd1, 4'd7, 4'd4, 16'd0};///home/dawsonjon/main.c : 49 {'a': 4, 'literal': 0, 'z': 7, 'trace': /home/dawsonjon/main.c : 49, 'op': 'addl'}
    instructions[4] = {5'd1, 4'd4, 4'd3, 16'd0};///home/dawsonjon/main.c : 49 {'a': 3, 'literal': 0, 'z': 4, 'trace': /home/dawsonjon/main.c : 49, 'op': 'addl'}
    instructions[5] = {5'd2, 4'd6, 4'd0, 16'd7};///home/dawsonjon/main.c : 49 {'z': 6, 'label': 7, 'trace': /home/dawsonjon/main.c : 49, 'op': 'call'}
    instructions[6] = {5'd3, 4'd0, 4'd0, 16'd0};///home/dawsonjon/main.c : 49 {'trace': /home/dawsonjon/main.c : 49, 'op': 'stop'}
    instructions[7] = {5'd1, 4'd3, 4'd3, 16'd3};///home/dawsonjon/main.c : 3 {'a': 3, 'literal': 3, 'z': 3, 'trace': /home/dawsonjon/main.c : 3, 'op': 'addl'}
    instructions[8] = {5'd1, 4'd8, 4'd4, 16'd0};///home/dawsonjon/main.c : 6 {'a': 4, 'literal': 0, 'z': 8, 'trace': /home/dawsonjon/main.c : 6, 'op': 'addl'}
    instructions[9] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 6, 'op': 'addl'}
    instructions[10] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 6 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 6, 'op': 'load'}
    instructions[11] = {5'd0, 4'd0, 4'd0, 16'd0};///home/dawsonjon/main.c : 6 {'literal': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[12] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[13] = {5'd6, 4'd0, 4'd0, 16'd51};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 51, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[14] = {5'd0, 4'd0, 4'd0, 16'd1};///home/dawsonjon/main.c : 6 {'literal': 1, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[15] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[16] = {5'd6, 4'd0, 4'd0, 16'd65};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 65, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[17] = {5'd0, 4'd0, 4'd0, 16'd2};///home/dawsonjon/main.c : 6 {'literal': 2, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[18] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[19] = {5'd6, 4'd0, 4'd0, 16'd79};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 79, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[20] = {5'd0, 4'd0, 4'd0, 16'd3};///home/dawsonjon/main.c : 6 {'literal': 3, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[21] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[22] = {5'd6, 4'd0, 4'd0, 16'd93};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 93, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[23] = {5'd0, 4'd0, 4'd0, 16'd4};///home/dawsonjon/main.c : 6 {'literal': 4, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[24] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[25] = {5'd6, 4'd0, 4'd0, 16'd107};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 107, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[26] = {5'd0, 4'd0, 4'd0, 16'd5};///home/dawsonjon/main.c : 6 {'literal': 5, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[27] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[28] = {5'd6, 4'd0, 4'd0, 16'd113};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 113, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[29] = {5'd0, 4'd0, 4'd0, 16'd6};///home/dawsonjon/main.c : 6 {'literal': 6, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[30] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[31] = {5'd6, 4'd0, 4'd0, 16'd127};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 127, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[32] = {5'd0, 4'd0, 4'd0, 16'd7};///home/dawsonjon/main.c : 6 {'literal': 7, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[33] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[34] = {5'd6, 4'd0, 4'd0, 16'd141};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 141, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[35] = {5'd0, 4'd0, 4'd0, 16'd8};///home/dawsonjon/main.c : 6 {'literal': 8, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[36] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[37] = {5'd6, 4'd0, 4'd0, 16'd155};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 155, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[38] = {5'd0, 4'd0, 4'd0, 16'd9};///home/dawsonjon/main.c : 6 {'literal': 9, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[39] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[40] = {5'd6, 4'd0, 4'd0, 16'd169};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 169, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[41] = {5'd0, 4'd0, 4'd0, 16'd10};///home/dawsonjon/main.c : 6 {'literal': 10, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[42] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[43] = {5'd6, 4'd0, 4'd0, 16'd181};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 181, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[44] = {5'd0, 4'd0, 4'd0, 16'd11};///home/dawsonjon/main.c : 6 {'literal': 11, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[45] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[46] = {5'd6, 4'd0, 4'd0, 16'd195};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 195, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[47] = {5'd0, 4'd0, 4'd0, 16'd12};///home/dawsonjon/main.c : 6 {'literal': 12, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'literal'}
    instructions[48] = {5'd5, 4'd0, 4'd8, 16'd0};///home/dawsonjon/main.c : 6 {'a': 8, 'b': 0, 'z': 0, 'trace': /home/dawsonjon/main.c : 6, 'op': 'equal'}
    instructions[49] = {5'd6, 4'd0, 4'd0, 16'd207};///home/dawsonjon/main.c : 6 {'a': 0, 'label': 207, 'trace': /home/dawsonjon/main.c : 6, 'op': 'jmp_if_true'}
    instructions[50] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 6 {'label': 219, 'trace': /home/dawsonjon/main.c : 6, 'op': 'goto'}
    instructions[51] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 8 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 8, 'op': 'addl'}
    instructions[52] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 8 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 8, 'op': 'addl'}
    instructions[53] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 8 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 8, 'op': 'load'}
    instructions[54] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 8 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 8, 'op': 'store'}
    instructions[55] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 8 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 8, 'op': 'addl'}
    instructions[56] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 8 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 8, 'op': 'addl'}
    instructions[57] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 8 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 8, 'op': 'addl'}
    instructions[58] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 8 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 8, 'op': 'load'}
    instructions[59] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 8 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 8, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[60] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 8 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 8, 'op': 'load'}
    instructions[61] = {5'd9, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 8 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 8, 'op': 'add'}
    instructions[62] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 8 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 8, 'op': 'addl'}
    instructions[63] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 8 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 8, 'op': 'store'}
    instructions[64] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 9 {'label': 219, 'trace': /home/dawsonjon/main.c : 9, 'op': 'goto'}
    instructions[65] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 11 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 11, 'op': 'addl'}
    instructions[66] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 11 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 11, 'op': 'addl'}
    instructions[67] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 11 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 11, 'op': 'load'}
    instructions[68] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 11 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 11, 'op': 'store'}
    instructions[69] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 11 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 11, 'op': 'addl'}
    instructions[70] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 11 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 11, 'op': 'addl'}
    instructions[71] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 11 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 11, 'op': 'addl'}
    instructions[72] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 11 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 11, 'op': 'load'}
    instructions[73] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 11 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 11, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[74] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 11 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 11, 'op': 'load'}
    instructions[75] = {5'd10, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 11 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 11, 'op': 'subtract'}
    instructions[76] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 11 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 11, 'op': 'addl'}
    instructions[77] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 11 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 11, 'op': 'store'}
    instructions[78] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 12 {'label': 219, 'trace': /home/dawsonjon/main.c : 12, 'op': 'goto'}
    instructions[79] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 14 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 14, 'op': 'addl'}
    instructions[80] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 14 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 14, 'op': 'addl'}
    instructions[81] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 14 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 14, 'op': 'load'}
    instructions[82] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 14 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 14, 'op': 'store'}
    instructions[83] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 14 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 14, 'op': 'addl'}
    instructions[84] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 14 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 14, 'op': 'addl'}
    instructions[85] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 14 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 14, 'op': 'addl'}
    instructions[86] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 14 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 14, 'op': 'load'}
    instructions[87] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 14 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 14, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[88] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 14 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 14, 'op': 'load'}
    instructions[89] = {5'd11, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 14 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 14, 'op': 'multiply'}
    instructions[90] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 14 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 14, 'op': 'addl'}
    instructions[91] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 14 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 14, 'op': 'store'}
    instructions[92] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 15 {'label': 219, 'trace': /home/dawsonjon/main.c : 15, 'op': 'goto'}
    instructions[93] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 17 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 17, 'op': 'addl'}
    instructions[94] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 17 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 17, 'op': 'addl'}
    instructions[95] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 17 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 17, 'op': 'load'}
    instructions[96] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 17 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 17, 'op': 'store'}
    instructions[97] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 17 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 17, 'op': 'addl'}
    instructions[98] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 17 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 17, 'op': 'addl'}
    instructions[99] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 17 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 17, 'op': 'addl'}
    instructions[100] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 17 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 17, 'op': 'load'}
    instructions[101] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 17 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 17, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[102] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 17 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 17, 'op': 'load'}
    instructions[103] = {5'd12, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 17 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 17, 'op': 'divide'}
    instructions[104] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 17 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 17, 'op': 'addl'}
    instructions[105] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 17 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 17, 'op': 'store'}
    instructions[106] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 18 {'label': 219, 'trace': /home/dawsonjon/main.c : 18, 'op': 'goto'}
    instructions[107] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 20 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 20, 'op': 'addl'}
    instructions[108] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 20 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 20, 'op': 'addl'}
    instructions[109] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 20 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 20, 'op': 'load'}
    instructions[110] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 20 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 20, 'op': 'addl'}
    instructions[111] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 20 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 20, 'op': 'store'}
    instructions[112] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 21 {'label': 219, 'trace': /home/dawsonjon/main.c : 21, 'op': 'goto'}
    instructions[113] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 23 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 23, 'op': 'addl'}
    instructions[114] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 23 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 23, 'op': 'addl'}
    instructions[115] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 23 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 23, 'op': 'load'}
    instructions[116] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 23 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 23, 'op': 'store'}
    instructions[117] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 23 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 23, 'op': 'addl'}
    instructions[118] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 23 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 23, 'op': 'addl'}
    instructions[119] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 23 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 23, 'op': 'addl'}
    instructions[120] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 23 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 23, 'op': 'load'}
    instructions[121] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 23 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 23, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[122] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 23 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 23, 'op': 'load'}
    instructions[123] = {5'd13, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 23 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 23, 'op': 'shift_left'}
    instructions[124] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 23 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 23, 'op': 'addl'}
    instructions[125] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 23 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 23, 'op': 'store'}
    instructions[126] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 24 {'label': 219, 'trace': /home/dawsonjon/main.c : 24, 'op': 'goto'}
    instructions[127] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 26 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 26, 'op': 'addl'}
    instructions[128] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 26 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 26, 'op': 'addl'}
    instructions[129] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 26 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 26, 'op': 'load'}
    instructions[130] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 26 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 26, 'op': 'store'}
    instructions[131] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 26 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 26, 'op': 'addl'}
    instructions[132] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 26 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 26, 'op': 'addl'}
    instructions[133] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 26 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 26, 'op': 'addl'}
    instructions[134] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 26 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 26, 'op': 'load'}
    instructions[135] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 26 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 26, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[136] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 26 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 26, 'op': 'load'}
    instructions[137] = {5'd14, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 26 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 26, 'op': 'shift_right'}
    instructions[138] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 26 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 26, 'op': 'addl'}
    instructions[139] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 26 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 26, 'op': 'store'}
    instructions[140] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 27 {'label': 219, 'trace': /home/dawsonjon/main.c : 27, 'op': 'goto'}
    instructions[141] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 29 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 29, 'op': 'addl'}
    instructions[142] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 29 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 29, 'op': 'addl'}
    instructions[143] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 29 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 29, 'op': 'load'}
    instructions[144] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 29 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 29, 'op': 'store'}
    instructions[145] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 29 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 29, 'op': 'addl'}
    instructions[146] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 29 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 29, 'op': 'addl'}
    instructions[147] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 29 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 29, 'op': 'addl'}
    instructions[148] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 29 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 29, 'op': 'load'}
    instructions[149] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 29 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 29, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[150] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 29 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 29, 'op': 'load'}
    instructions[151] = {5'd15, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 29 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 29, 'op': 'and'}
    instructions[152] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 29 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 29, 'op': 'addl'}
    instructions[153] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 29 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 29, 'op': 'store'}
    instructions[154] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 30 {'label': 219, 'trace': /home/dawsonjon/main.c : 30, 'op': 'goto'}
    instructions[155] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 32 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 32, 'op': 'addl'}
    instructions[156] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 32 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 32, 'op': 'addl'}
    instructions[157] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 32 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 32, 'op': 'load'}
    instructions[158] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 32 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 32, 'op': 'store'}
    instructions[159] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 32 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 32, 'op': 'addl'}
    instructions[160] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 32 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 32, 'op': 'addl'}
    instructions[161] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 32 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 32, 'op': 'addl'}
    instructions[162] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 32 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 32, 'op': 'load'}
    instructions[163] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 32 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 32, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[164] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 32 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 32, 'op': 'load'}
    instructions[165] = {5'd16, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 32 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 32, 'op': 'or'}
    instructions[166] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 32 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 32, 'op': 'addl'}
    instructions[167] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 32 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 32, 'op': 'store'}
    instructions[168] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 33 {'label': 219, 'trace': /home/dawsonjon/main.c : 33, 'op': 'goto'}
    instructions[169] = {5'd0, 4'd8, 4'd0, 16'd0};///home/dawsonjon/main.c : 35 {'literal': 0, 'z': 8, 'trace': /home/dawsonjon/main.c : 35, 'op': 'literal'}
    instructions[170] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 35 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 35, 'op': 'store'}
    instructions[171] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 35 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 35, 'op': 'addl'}
    instructions[172] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 35 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 35, 'op': 'addl'}
    instructions[173] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 35 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 35, 'op': 'addl'}
    instructions[174] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 35 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 35, 'op': 'load'}
    instructions[175] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 35 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 35, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[176] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 35 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 35, 'op': 'load'}
    instructions[177] = {5'd5, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 35 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 35, 'op': 'equal'}
    instructions[178] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 35 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 35, 'op': 'addl'}
    instructions[179] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 35 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 35, 'op': 'store'}
    instructions[180] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 36 {'label': 219, 'trace': /home/dawsonjon/main.c : 36, 'op': 'goto'}
    instructions[181] = {5'd1, 4'd8, 4'd4, 16'd2};///home/dawsonjon/main.c : 38 {'a': 4, 'literal': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 38, 'op': 'addl'}
    instructions[182] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 38 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 38, 'op': 'addl'}
    instructions[183] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 38 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 38, 'op': 'load'}
    instructions[184] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 38 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 38, 'op': 'store'}
    instructions[185] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 38 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 38, 'op': 'addl'}
    instructions[186] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 38 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 38, 'op': 'addl'}
    instructions[187] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 38 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 38, 'op': 'addl'}
    instructions[188] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 38 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 38, 'op': 'load'}
    instructions[189] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 38 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 38, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[190] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 38 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 38, 'op': 'load'}
    instructions[191] = {5'd17, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 38 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 38, 'op': 'xor'}
    instructions[192] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 38 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 38, 'op': 'addl'}
    instructions[193] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 38 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 38, 'op': 'store'}
    instructions[194] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 39 {'label': 219, 'trace': /home/dawsonjon/main.c : 39, 'op': 'goto'}
    instructions[195] = {5'd0, 4'd8, 4'd0, 16'd1};///home/dawsonjon/main.c : 41 {'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 41, 'op': 'literal'}
    instructions[196] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 41 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 41, 'op': 'store'}
    instructions[197] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 41 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 41, 'op': 'addl'}
    instructions[198] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 41 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 41, 'op': 'addl'}
    instructions[199] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 41 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 41, 'op': 'addl'}
    instructions[200] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 41 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 41, 'op': 'load'}
    instructions[201] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 41 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 41, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[202] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 41 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 41, 'op': 'load'}
    instructions[203] = {5'd9, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 41 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 41, 'op': 'add'}
    instructions[204] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 41 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 41, 'op': 'addl'}
    instructions[205] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 41 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 41, 'op': 'store'}
    instructions[206] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 42 {'label': 219, 'trace': /home/dawsonjon/main.c : 42, 'op': 'goto'}
    instructions[207] = {5'd0, 4'd8, 4'd0, 16'd1};///home/dawsonjon/main.c : 44 {'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 44, 'op': 'literal'}
    instructions[208] = {5'd8, 4'd0, 4'd3, 16'd8};///home/dawsonjon/main.c : 44 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /home/dawsonjon/main.c : 44, 'op': 'store'}
    instructions[209] = {5'd1, 4'd3, 4'd3, 16'd1};///home/dawsonjon/main.c : 44 {'a': 3, 'literal': 1, 'z': 3, 'trace': /home/dawsonjon/main.c : 44, 'op': 'addl'}
    instructions[210] = {5'd1, 4'd8, 4'd4, 16'd1};///home/dawsonjon/main.c : 44 {'a': 4, 'literal': 1, 'z': 8, 'trace': /home/dawsonjon/main.c : 44, 'op': 'addl'}
    instructions[211] = {5'd1, 4'd2, 4'd8, 16'd0};///home/dawsonjon/main.c : 44 {'a': 8, 'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 44, 'op': 'addl'}
    instructions[212] = {5'd4, 4'd8, 4'd2, 16'd0};///home/dawsonjon/main.c : 44 {'a': 2, 'z': 8, 'trace': /home/dawsonjon/main.c : 44, 'op': 'load'}
    instructions[213] = {5'd1, 4'd3, 4'd3, -16'd1};///home/dawsonjon/main.c : 44 {'a': 3, 'comment': 'pop', 'trace': /home/dawsonjon/main.c : 44, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[214] = {5'd4, 4'd10, 4'd3, 16'd0};///home/dawsonjon/main.c : 44 {'a': 3, 'z': 10, 'trace': /home/dawsonjon/main.c : 44, 'op': 'load'}
    instructions[215] = {5'd10, 4'd8, 4'd8, 16'd10};///home/dawsonjon/main.c : 44 {'a': 8, 'z': 8, 'b': 10, 'trace': /home/dawsonjon/main.c : 44, 'op': 'subtract'}
    instructions[216] = {5'd1, 4'd2, 4'd4, 16'd1};///home/dawsonjon/main.c : 44 {'a': 4, 'literal': 1, 'z': 2, 'trace': /home/dawsonjon/main.c : 44, 'op': 'addl'}
    instructions[217] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 44 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 44, 'op': 'store'}
    instructions[218] = {5'd7, 4'd0, 4'd0, 16'd219};///home/dawsonjon/main.c : 45 {'label': 219, 'trace': /home/dawsonjon/main.c : 45, 'op': 'goto'}
    instructions[219] = {5'd0, 4'd8, 4'd0, 16'd0};///home/dawsonjon/main.c : 47 {'literal': 0, 'z': 8, 'trace': /home/dawsonjon/main.c : 47, 'op': 'literal'}
    instructions[220] = {5'd0, 4'd2, 4'd0, 16'd0};///home/dawsonjon/main.c : 47 {'literal': 0, 'z': 2, 'trace': /home/dawsonjon/main.c : 47, 'op': 'literal'}
    instructions[221] = {5'd8, 4'd0, 4'd2, 16'd8};///home/dawsonjon/main.c : 47 {'a': 2, 'b': 8, 'trace': /home/dawsonjon/main.c : 47, 'op': 'store'}
    instructions[222] = {5'd1, 4'd3, 4'd4, 16'd0};///home/dawsonjon/main.c : 47 {'a': 4, 'literal': 0, 'z': 3, 'trace': /home/dawsonjon/main.c : 47, 'op': 'addl'}
    instructions[223] = {5'd1, 4'd4, 4'd7, 16'd0};///home/dawsonjon/main.c : 47 {'a': 7, 'literal': 0, 'z': 4, 'trace': /home/dawsonjon/main.c : 47, 'op': 'addl'}
    instructions[224] = {5'd18, 4'd0, 4'd6, 16'd0};///home/dawsonjon/main.c : 47 {'a': 6, 'trace': /home/dawsonjon/main.c : 47, 'op': 'return'}
  end

  
  always @(posedge clk)
  begin
    load_data <= memory[load_address];
    if(store_enable && state == execute) begin
      if (store_address > 1023) begin
        exception <= 1'b1;
      end
      memory[store_address] <= store_data;
    end
    if (rst==1'b1) begin
      exception <= 1'b0;
    end
  end


  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 1 -- FETCH INSTRUCTION
  //                                                                            
  
  always @(posedge clk)
  begin
    //implement memory for instructions
    if (state == instruction_fetch || state == operand_fetch || state == execute) begin
      instruction <= instructions[program_counter];
      program_counter_1 <= program_counter;
    end
  end

  assign opcode    = instruction[28:24];
  assign address_z = instruction[23:20];
  assign address_a = instruction[19:16];
  assign address_b = instruction[3:0];
  assign literal   = instruction[15:0];
  assign forward_a = (address_a_2 == address_z_3 && write_enable);
  assign forward_b = (address_b_2 == address_z_3 && write_enable);

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 2 -- FETCH OPERANDS
  //                                                                            
  
  always @(posedge clk)
  begin
    if (write_enable) begin
      registers[address_z_3] <= result;
    end
    if (state == operand_fetch || state == execute) begin
      opcode_2 <= opcode;
      literal_2 <= literal;
      address_a_2 <= address_a;
      address_b_2 <= address_b;
      address_z_2 <= address_z;
      program_counter_2 <= program_counter_1;
    end
  end
  assign register_a = registers[address_a_2];
  assign register_b = registers[address_b_2];
  assign operand_a = forward_a?result:register_a;
  assign operand_b = forward_b?result:register_b;
  assign store_address = operand_a;
  assign load_address = operand_a;
  assign store_data = operand_b;
  assign store_enable = (opcode_2==8);

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 3 -- EXECUTE
  //                                                                            
  
  always @(posedge clk)
  begin

  write_enable <= 0;
  timer_clock <= timer_clock + 1;
  case(state)

    //instruction_fetch
    instruction_fetch: begin
      program_counter <= program_counter + 1;
      state <= operand_fetch;
    end
    //operand_fetch
    operand_fetch: begin
      program_counter <= program_counter + 1;
      state <= execute;
    end
    //execute
    execute: begin
      program_counter <= program_counter + 1;
      address_z_3 <= address_z_2;
      case(opcode_2)

        //literal
        16'd0:
        begin
          result<=$signed(literal_2);
          write_enable <= 1;
        end

        //addl
        16'd1:
        begin
          result<=operand_a + literal_2;
          write_enable <= 1;
        end

        //call
        16'd2:
        begin
          result <= program_counter_2 + 1;
          write_enable <= 1;
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //stop
        16'd3:
        begin
        sate <= stop;
        end

        //load
        16'd4:
        begin
          state <= load;
        end

        //equal
        16'd5:
        begin
          result <= operand_a == operand_b;
          write_enable <= 1;
        end

        //jmp_if_true
        16'd6:
        begin
          if (operand_a != 0) begin
            program_counter <= literal_2;
            state <= instruction_fetch;
          end
        end

        //goto
        16'd7:
        begin
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //store
        16'd8:
        begin
        end

        //add
        16'd9:
        begin
          long_result = operand_a + operand_b;
          result <= long_result[31:0];
          carry[0] <= long_result[32];
          write_enable <= 1;
        end

        //subtract
        16'd10:
        begin
          long_result = operand_a + (~operand_b) + 1;
          result <= long_result[31:0];
          carry[0] <= ~long_result[32];
          write_enable <= 1;
        end

        //multiply
        16'd11:
        begin
          product_a <= operand_a[15:0]  * operand_b[15:0];
          product_b <= operand_a[15:0]  * operand_b[31:16];
          product_c <= operand_a[31:16] * operand_b[15:0];
          product_d <= operand_a[31:16] * operand_b[31:16];
          state <= multiply;
        end

        //divide
        16'd12:
        begin
          quotient_sign <= operand_a[31] ^ operand_b[31];
          dividend  <= operand_a;
          divisor <= operand_b;
          if (operand_a[31]) begin
            dividend <= -operand_a;
          end
          if (operand_b[31]) begin
            divisor <= -operand_b;
          end
          timer <= 32;
          remainder <= 0;
          quotient <= 0;
          state <= divide;
        end

        //shift_left
        16'd13:
        begin
          if(operand_b < 32) begin
            result <= operand_a << operand_b;
            carry <= operand_a >> (32-operand_b);
          end else begin
            result <= 0;
            carry <= operand_a;
          end
          write_enable <= 1;
        end

        //shift_right
        16'd14:
        begin
          if(operand_b < 32) begin
            result <= $signed(operand_a) >>> operand_b;
            carry <= operand_a << (32-operand_b);
          end else begin
            result <= operand_a[31]?-1:0;
            carry <= operand_a;
          end
          write_enable <= 1;
        end

        //and
        16'd15:
        begin
          result <= operand_a & operand_b;
          write_enable <= 1;
        end

        //or
        16'd16:
        begin
          result <= operand_a | operand_b;
          write_enable <= 1;
        end

        //xor
        16'd17:
        begin
          result <= operand_a ^ operand_b;
          write_enable <= 1;
        end

        //return
        16'd18:
        begin
          program_counter <= operand_a;
          state <= instruction_fetch;
        end

      endcase

    end

    multiply:
    begin
      long_result = product_a +
                    (product_b << 16) +
                    (product_c << 16) +
                    (product_d << 32);
      result <= long_result[31:0];
      carry <= long_result[63:32];
      write_enable <= 1;
      state <= execute;
    end

    divide:
    begin
      if (timer) begin
        timer <= timer - 1;
      end else begin
        if (quotient_sign) begin
          result <= -quotient;
        end else begin
          result <= quotient;
        end
        state <= execute;
        write_enable <= 1;
      end
    end

    load:
    begin
        result <= load_data;
        write_enable <= 1;
        state <= execute;
    end

    wait_state:
    begin
      if (timer) begin
        timer <= timer - 1;
      end else begin
        state <= execute;
      end
    end

    stop:
    begin
    end

    endcase

    //divider kernel logic
    repeat (1) begin
      shifter = {remainder[30:0], dividend[31]};
      difference = shifter - divisor;
      dividend = dividend << 1;
      if (difference[32]) begin
        remainder = shifter;
        quotient = quotient << 1;
      end else begin
        remainder = difference[31:0];
        quotient = quotient << 1 | 1;
      end
    end

    if (rst == 1'b1) begin
      timer <= 0;
      timer_clock <= 0;
      program_counter <= 0;
      address_z_3 <= 0;
      result <= 0;
      a = 0;
      b = 0;
      z = 0;
      state <= instruction_fetch;
    end
  end

endmodule
